version: "3"
services:
  pihole:
    build: ./pihole
    ports:
      - "443:443"
      - "53:53"
      - "53:53/udp"
      - "67:67"
    environment:
      DNS1: "208.67.222.222"
      DNS2: "208.67.220.220"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
      ServerIP: "${SERVER_IP}"
  internal_nginx:
    build: ./internal_nginx
    ports:
      - "${WEB_PORT}:80"
