version: "3"
services:

  internal_nginx:
    extends:
      file: docker-compose.yml
      service: internal_nginx

  pihole:
    extends:
      file: docker-compose.yml
      service: pihole

  home_assistant:
    extends:
      file: docker-compose.yml
      service: home_assistant

  node_red:
    extends:
      file: docker-compose.yml
      service: node_red

  certbot:
    extends:
      file: docker-compose.yml
      service: certbot

  bastion:
    extends:
      file: docker-compose.yml
      service: bastion

  jenkins:
    extends:
      file: docker-compose.yml
      service: jenkins

  prometheus:
    extends:
      file: docker-compose.yml
      service: prometheus

  cadvisor:
    extends:
      file: docker-compose.yml
      service: cadvisor

  logspout:
    extends:
      file: docker-compose.yml
      service: logspout

  logstash:
    extends:
      file: docker-compose.yml
      service: logstash

  elasticsearch:
    extends:
      file: docker-compose.yml
      service: elasticsearch

  kibana:
    extends:
      file: docker-compose.yml
      service: kibana

volumes:
  home_assistant_config:
  node_red_data:
  certbot_conf:
  certbot_www:
  jenkins_home:
