version: "3"
services:

  internal_nginx:
    build: ./internal_nginx
    ports:
      - "${SERVER_IP}:${WEB_PORT}:80"
    depends_on:
      - pihole
      - home_assistant
      - node_red
      - jenkins
      - prometheus
      - kibana

  # external_nginx:
  #   build: ./external_nginx
  #   ports:
  #     - "${EXTERNAL_SERVER_IP}:80:80"
  #     - "${EXTERNAL_SERVER_IP}:443:443"
  #   depends_on:
  #     - home_assistant

  pihole:
    build: ./pihole
    ports:
      - "${SERVER_IP}:53:53"
      - "${SERVER_IP}:53:53/udp"
      - "${SERVER_IP}:67:67"
    environment:
      DNS1: "208.67.222.222"
      DNS2: "208.67.220.220"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
      ServerIP: "${SERVER_IP}"

  home_assistant:
    build: ./home_assistant
    environment:
      HOME_LATITUDE: "${HOME_LATITUDE}"
      HOME_LONGITUDE: "${HOME_LONGITUDE}"
      HOME_ELEVATION: "${HOME_ELEVATION}"
      SIMPLISAFE_USERNAME: "${SIMPLISAFE_USERNAME}"
      SIMPLISAFE_PASSWORD: "${SIMPLISAFE_PASSWORD}"
      DARKSKY_API_KEY: "${DARKSKY_API_KEY}"
      NEST_CLIENT_ID: "${NEST_CLIENT_ID}"
      NEST_SECRET: "${NEST_SECRET}"
    volumes:
      - "home_assistant_config:/config"
      # - "/dev/ttyUSB1:/dev/ttyUSB1"
      # - "/dev/ttyUSB0:/dev/ttyUSB0"

  node_red:
    build: ./node_red
    volumes:
      - "node_red_data:/data"

  certbot:
    image: certbot/certbot
    volumes:
      - "certbot_conf:/etc/letsencrypt"
      - "certbot_www:/var/www/certbot"

  bastion:
    build: ./bastion

  jenkins:
    image: jenkins/jenkins:alpine
    volumes:
      - "jenkins_home:/var/jenkins_home"

  prometheus:
    build: ./prometheus

  cadvisor:
    image: google/cadvisor:latest
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  logspout:
    image: gliderlabs/logspout
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    command: syslog://logstash:5000
    depends_on:
      - logstash

  logstash:
    build: ./logstash
    environment:
      LOGSPOUT: ignore
    depends_on:
      - elasticsearch

  elasticsearch:
    image: elasticsearch:7.2.0
    environment:
      discovery.type: single-node

  kibana:
    build: ./kibana
    depends_on:
      - elasticsearch

volumes:
  home_assistant_config:
  node_red_data:
  certbot_conf:
  certbot_www:
  jenkins_home:
