version: '3'
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "443"
      - "53"
      - "53/udp"
      - "67"
      - "80"
    environment:
      DNS1: "208.67.222.222"
      DNS2: "208.67.220.220"
