version: "3"
services:

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginx_certs:/etc/nginx/certs"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_vhost:/etc/nginx/vhost.d"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      DEFAULT_EMAIL: "kevindurb@gmail.com"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginx_certs:/etc/nginx/certs"
      - "nginx_html:/usr/share/nginx/html"
      - "nginx_vhost:/etc/nginx/vhost.d"

  pihole:
    build: ./pihole
    ports:
      - "${SERVER_IP}:53:53"
      - "${SERVER_IP}:53:53/udp"
      - "${SERVER_IP}:67:67"
    environment:
      DNS1: "208.67.222.222"
      DNS2: "208.67.220.220"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
      ServerIP: "${SERVER_IP}"
      VIRTUAL_HOST: "pihole.*,pi.hole"
      VIRTUAL_PORT: "80"
      NETWORK_ACCESS: "internal"

  home_assistant:
    build: ./home_assistant
    environment:
      HOME_LATITUDE: "${HOME_LATITUDE}"
      HOME_LONGITUDE: "${HOME_LONGITUDE}"
      HOME_ELEVATION: "${HOME_ELEVATION}"
      SIMPLISAFE_USERNAME: "${SIMPLISAFE_USERNAME}"
      SIMPLISAFE_PASSWORD: "${SIMPLISAFE_PASSWORD}"
      DARKSKY_API_KEY: "${DARKSKY_API_KEY}"
      NEST_CLIENT_ID: "${NEST_CLIENT_ID}"
      NEST_SECRET: "${NEST_SECRET}"
      VIRTUAL_HOST: "hass.*"
      VIRTUAL_PORT: "8123"
      LETSENCRYPT_HOST: "hass.kevindurbin.com"
    volumes:
      - "home_assistant_config:/config"
      # - "/dev/ttyUSB1:/dev/ttyUSB1"
      # - "/dev/ttyUSB0:/dev/ttyUSB0"

  node_red:
    build: ./node_red
    environment:
      VIRTUAL_HOST: "hass.*"
      VIRTUAL_PORT: "1880"
      NETWORK_ACCESS: "internal"
    volumes:
      - "node_red_data:/data"

  # bastion:
  #   build: ./bastion
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #     - "./:/var/home"

  # jenkins:
  #   image: jenkins/jenkins:centos
  #   volumes:
  #     - "jenkins_home:/var/jenkins_home"

  prometheus:
    build: ./prometheus
    environment:
      VIRTUAL_HOST: "prom.*"
      VIRTUAL_PORT: "9090"
      NETWORK_ACCESS: "internal"
    volumes:
    - prometheus:/etc/prometheus

  cadvisor:
    image: google/cadvisor:latest
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  # logstash:
  #   build: ./logstash
  #   ports:
  #     - "12201:12201"
  #   depends_on:
  #     - elasticsearch

  # elasticsearch:
  #   image: elasticsearch:7.2.0
  #   environment:
  #     discovery.type: single-node

  # kibana:
  #   build: ./kibana
  #   depends_on:
  #     - elasticsearch

volumes:
  home_assistant_config:
  node_red_data:
  jenkins_home:
  prometheus:
  nginx_vhost:
  nginx_certs:
  nginx_html:
