version: "3"
services:

  nginx:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "nginx_certs:/etc/nginx/certs:ro"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"
      - "${PWD}/nginx_proxy/network_internal.conf:/etc/nginx/network_internal.conf"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    environment:
      DEFAULT_EMAIL: "kevindurb@gmail.com"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "nginx_certs:/etc/nginx/certs:rw"
      - "nginx_vhost:/etc/nginx/vhost.d"
      - "nginx_html:/usr/share/nginx/html"

  pihole:
    image: pihole/pihole:latest
    ports:
      - "${SERVER_IP}:53:53"
      - "${SERVER_IP}:53:53/udp"
      - "${SERVER_IP}:67:67"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}/pihole/02-internal.conf:/etc/dnsmasq.d/02-internal.conf"
    environment:
      DNS1: "208.67.222.222"
      DNS2: "208.67.220.220"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
      ServerIP: "${SERVER_IP}"
      VIRTUAL_HOST: "pihole.*,pi.hole"
      VIRTUAL_PORT: "80"
      NETWORK_ACCESS: "internal"

  home_assistant:
    image: homeassistant/home-assistant:latest
    environment:
      HOME_LATITUDE: "${HOME_LATITUDE}"
      HOME_LONGITUDE: "${HOME_LONGITUDE}"
      HOME_ELEVATION: "${HOME_ELEVATION}"
      SIMPLISAFE_USERNAME: "${SIMPLISAFE_USERNAME}"
      SIMPLISAFE_PASSWORD: "${SIMPLISAFE_PASSWORD}"
      DARKSKY_API_KEY: "${DARKSKY_API_KEY}"
      NEST_CLIENT_ID: "${NEST_CLIENT_ID}"
      NEST_SECRET: "${NEST_SECRET}"
      VIRTUAL_HOST: "hass.kevindurbin.com"
      VIRTUAL_PORT: "8123"
      LETSENCRYPT_HOST: "hass.kevindurbin.com"
    volumes:
      - "${PWD}/home_assistant/config:/config"
    devices:
      - "/dev/ttyUSB1:/dev/ttyUSB1"
      - "/dev/ttyUSB0:/dev/ttyUSB0"

  node_red:
    image: nodered/node-red-docker:latest
    environment:
      VIRTUAL_HOST: "nodered.*"
      VIRTUAL_PORT: "1880"
      NETWORK_ACCESS: "internal"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "node_red_data:/data"
      - "${PWD}/node_red/settings.js:/data/settings.js"

  motioneye:
    image: ccrisan/motioneye:master-amd64
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "motioneye_etc:/etc/motioneye"
      - "motioneye_var_lib:/var/lib/motioneye"
    environment:
      LETSENCRYPT_HOST: "motioneye.kevindurbin.com"
      VIRTUAL_HOST: "motioneye.kevindurbin.com"
      VIRTUAL_PORT: "8765"

  prometheus:
    image: prom/prometheus:latest
    environment:
      VIRTUAL_HOST: "prom.*"
      VIRTUAL_PORT: "9090"
      NETWORK_ACCESS: "internal"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${PWD}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
      - prometheus:/etc/prometheus

  cadvisor:
    image: google/cadvisor:latest
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro

  nextcloud:
    image: nextcloud:stable-apache
    environment:
      # LETSENCRYPT_HOST: "nextcloud.kevindurbin.com"
      VIRTUAL_HOST: "nextcloud.kevindurbin.com"
      VIRTUAL_PORT: "80"
      NETWORK_ACCESS: "internal"
    volumes:
      - "/storage/nextcloud_data:/var/www/html"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_USER: "postgres"
    volumes:
      - "/storage/postgres_data:/var/lib/postgresql/data"

volumes:
  node_red_data:
  prometheus:
  nginx_certs:
  nginx_html:
  nginx_vhost:
  motioneye_etc:
  motioneye_var_lib:
