version: "3"
services:

  pihole:
    build: ./pihole
    ports:
      - "${SERVER_IP}:53:53"
      - "${SERVER_IP}:53:53/udp"
      - "${SERVER_IP}:67:67"
    environment:
      DNS1: "208.67.222.222"
      DNS2: "208.67.220.220"
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
      ServerIP: "${SERVER_IP}"

  internal_nginx:
    build: ./internal_nginx
    ports:
      - "${SERVER_IP}:${WEB_PORT}:80"

  external_nginx:
    build: ./external_nginx
    ports:
      - "${EXTERNAL_SERVER_IP}:80:80"
      - "${EXTERNAL_SERVER_IP}:443:443"

  home_assistant:
    build: ./home_assistant
    environment:
      HOME_LATITUDE: "${HOME_LATITUDE}"
      HOME_LONGITUDE: "${HOME_LONGITUDE}"
      HOME_ELEVATION: "${HOME_ELEVATION}"
      SIMPLISAFE_USERNAME: "${SIMPLISAFE_USERNAME}"
      SIMPLISAFE_PASSWORD: "${SIMPLISAFE_PASSWORD}"
      DARKSKY_API_KEY: "${DARKSKY_API_KEY}"
      NEST_CLIENT_ID: "${NEST_CLIENT_ID}"
      NEST_SECRET: "${NEST_SECRET}"
    volumes:
      - "home_assistant_config:/config"

  node_red:
    build: ./node_red
    volumes:
      - "node_red_data:/data"

  certbot:
    image: certbot/certbot
    volumes:
      - "certbot_conf:/etc/letsencrypt"
      - "certbot_www:/var/www/certbot"

  bastion:
    build: ./bastion

  jenkins:
    image: jenkins/jenkins:alpine

volumes:
  home_assistant_config:
  node_red_data:
  certbot_conf:
  certbot_www:
