version: "3"
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "443:443"
      - "53:53"
      - "53:53/udp"
      - "67:67"
      - "80:80"
    environment:
      DNS1: dnsmasq
      WEBPASSWORD: "${PIHOLE_WEBPASSWORD}"
      ServerIP: "${SERVER_IP}"
    depends_on: dnsmasq
  dnsmasq:
    build: ./dnsmasq/
    cap_add:
      - NET_ADMIN

