homeassistant:
  name: Home
  latitude: !env_var HOME_LATITUDE
  longitude: !env_var HOME_LONGITUDE
  elevation: !env_var HOME_ELEVATION
  unit_system: imperial
  time_zone: America/Denver

config:
frontend:
history:
logbook:
map:
person:
system_health:

notify:

simplisafe:
  accounts:
    - username: !env_var SIMPLISAFE_USERNAME
      password: !env_var SIMPLISAFE_PASSWORD

weather:
  platform: darksky
  api_key: !env_var DARKSKY_API_KEY

nest:
  client_id: !env_var NEST_CLIENT_ID
  client_secret: !env_var NEST_SECRET

zwave:
  usb_path: /dev/ttyUSB0

zha:
  usb_path: /dev/ttyUSB1
  database_path: /config/zigbee.db

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
zone: !include zones.yaml
